server:
  port: 3000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: movie-info-service
          uri: lb://movie-info-service
          predicates:
          - Path= /movies/**
        - id: rating-data-service
          uri: lb://rating-data-service
          predicates:
            - Path= /ratings/**
        - id: movie-catalogue-service
          uri: lb://movie-catalogue-service
          predicates:
              - Path= /catalogue/**

